export const MUNICIPIOS_POR_PROVINCIA: Record<string, string[]> = {
  "CABA": [
    "Agronomía","Almagro","Balvanera","Barracas","Belgrano","Boedo","Caballito",
    "Chacarita","Coghlan","Colegiales","Constitución","Flores","Floresta","La Boca",
    "La Paternal","Liniers","Mataderos","Monte Castro","Montserrat","Nueva Pompeya",
    "Núñez","Palermo","Parque Avellaneda","Parque Chacabuco","Parque Chas",
    "Parque Patricios","Puerto Madero","Recoleta","Retiro","Saavedra","San Cristóbal",
    "San Nicolás","San Telmo","Versalles","Villa Crespo","Villa del Parque",
    "Villa Devoto","Villa General Mitre","Villa Lugano","Villa Luro","Villa Ortúzar",
    "Villa Pueyrredón","Villa Real","Villa Riachuelo","Villa Santa Rita","Villa Soldati",
    "Villa Urquiza","Villa Vélez Sarsfield",
  ],
  "Buenos Aires": [
    "Tigre","San Isidro","San Fernando","Vicente López","San Martín","Tres de Febrero",
    "Pilar","Escobar","Malvinas Argentinas","José C. Paz","San Miguel","Hurlingham",
    "Ituzaingó","Moreno","General Rodríguez","Marcos Paz","Luján","Mercedes",
    "La Matanza","Merlo","Morón","Cañuelas",
    "Avellaneda","Lanús","Lomas de Zamora","Quilmes","Berazategui","Florencio Varela",
    "Almirante Brown","Esteban Echeverría","Ezeiza","Presidente Perón","San Vicente",
    "Berisso","Ensenada","Brandsen",
    "La Plata","Mar del Plata","Bahía Blanca","Tandil","Olavarría","Junín",
    "Pergamino","San Nicolás de los Arroyos","Zárate","Campana","San Pedro","Ramallo",
    "Necochea","Tres Arroyos","Coronel Suárez","Benito Juárez","Bolívar","Saladillo",
    "Chivilcoy","Bragado","9 de Julio","Lincoln","Pehuajó","Trenque Lauquen",
    "Rivadavia","General Villegas","Salto","Rojas","San Antonio de Areco",
    "Chascomús","Dolores","Maipú","Ayacucho","Rauch","General Lavalle",
    "Azul","Las Flores","General Alvear","Roque Pérez","Lobos","Monte",
    "Lobería","Balcarce","Mar Chiquita","General Pueyrredón","Miramar",
    "Coronel Dorrego","Puan","Coronel Rosales","Monte Hermoso",
    "Villa Gesell","Pinamar","Mar de Ajó","Santa Teresita","San Clemente del Tuyú",
    "Partido de la Costa","General Madariaga","Tordillo","Castelli",
    "General Guido","Pila","Lezama","Magdalena","Punta Indio",
    "Alberti","Carlos Casares","Carlos Tejedor","Daireaux",
    "General Arenales","General Paz","General Pinto","General Viamonte",
    "Hipólito Yrigoyen","Leandro N. Alem","Navarro","Nueve de Julio",
    "Pellegrini","Suipacha","Tapalqué",
  ],
  "Catamarca": [
    "San Fernando del Valle de Catamarca","Andalgalá","Tinogasta","Santa María",
    "Belén","Fiambalá","Recreo","Chumbicha","Huillapima","Pomán",
    "Antofagasta de la Sierra","Aconquija","Capayán","El Alto","Icaño",
    "Londres","Mutquín","Paclín","Santa Cruz","Valle Viejo",
  ],
  "Chaco": [
    "Resistencia","Barranqueras","Fontana","Villa Ángela","Presidencia Roque Sáenz Peña",
    "Charata","General San Martín","Quitilipi","Las Breñas","Juan José Castelli",
    "Tres Isletas","Corzuela","Machagai","Avia Terai","Pampa del Indio","El Sauzalito",
    "Presidencia de la Plaza","Hermoso Campo","La Clotilde","Makallé","Napenay",
    "Santa Sylvina","Taco Pozo","Villa Berthet",
  ],
  "Chubut": [
    "Rawson","Comodoro Rivadavia","Esquel","Trelew","Puerto Madryn","Rada Tilly",
    "Sarmiento","Río Mayo","Lago Puelo","El Bolsón","Gaiman","Dolavon","28 de Julio",
    "Alto Río Senguer","Camarones","Cholila","Corcovado","Gobernador Costa",
    "Gualjaina","José de San Martín","Lago Blanco","Las Plumas","Los Altares",
    "Paso de Indios","Puerto Pirámides","Río Pico","Tecka",
  ],
  "Córdoba": [
    "Córdoba capital","Villa María","San Francisco","Río Cuarto","Río Tercero","Alta Gracia",
    "Villa Carlos Paz","La Falda","Cosquín","Bell Ville","Marcos Juárez","Jesús María",
    "Unquillo","Mendiolaza","Malagueño","Pilar","Oncativo","General Cabrera",
    "Laboulaye","Leones","Oliva","La Carlota","General Deheza","Villa Allende",
    "Saldán","Dean Funes","Cruz del Eje","Mina Clavero","Villa General Belgrano",
    "Santa Rosa de Calamuchita","Embalse","Villa Cura Brochero","Huerta Grande",
    "Arroyito","Berrotarán","Bialet Massé","Capilla del Monte",
    "Corral de Bustos","Despeñaderos","Freyre","La Granja","La Para",
    "La Playosa","Las Varillas","Luque","Morteros","Monte Buey","Noetinger",
    "Obispo Trejo","Porteña","Sacanta","San Marcos Sierras","Serrano",
    "Toledo","Tancacha","Villa del Rosario","Villa Dolores","Villa Giardino",
    "Villa Huidobro","Villa Nueva","Villa de María","Wenceslao Escalante",
  ],
  "Corrientes": [
    "Corrientes capital","Goya","Curuzú Cuatiá","Mercedes","Paso de los Libres",
    "Santo Tomé","Bella Vista","Esquina","Monte Caseros","Ituzaingó","San Luis del Palmar",
    "Mburucuyá","Saladas","General Alvear","Sauce","Yapeyú","Chavarría",
    "Concepción","Gobernador Virasoro","Itatí","La Cruz","Loreto","Perugorría",
    "San Cosme","San Miguel","San Roque","Santa Lucía",
  ],
  "Entre Ríos": [
    "Paraná","Concordia","Gualeguaychú","Concepción del Uruguay","Villaguay","La Paz",
    "Colón","Federación","Victoria","Chajarí","San José","Basavilbaso",
    "Crespo","Diamante","Federal","Nogoyá","Rosario del Tala","Gualeguay",
    "Bovril","Ceibas","Cerrito","Don Cristóbal","General Campos","General Galarza",
    "General Ramírez","Hernandarias","La Criolla","Lucas González","Maciá",
    "María Grande","Urdinarrain","Viale","Villa Elisa","Villa Paranacito",
  ],
  "Formosa": [
    "Formosa capital","Clorinda","Pirané","El Colorado","Las Lomitas","Ibarreta",
    "Ingeniero Juárez","Gran Guardia","Laguna Blanca","Comandante Fontana",
    "Buena Vista","El Espinillo","Herradura","Palo Santo","Siete Palmas",
  ],
  "Jujuy": [
    "San Salvador de Jujuy","San Pedro de Jujuy","Palpalá","Libertador General San Martín",
    "Humahuaca","Tilcara","Purmamarca","La Quiaca","Abra Pampa","Perico",
    "Monterrico","El Carmen","Fraile Pintado","Yala","Caimancito","Calilegua",
    "El Aguilar","Hipólito Yrigoyen","Huacalera","La Esperanza","Ledesma",
    "Maimará","Rinconada","Santa Catalina","Susques","Tres Cruces","Valle Grande","Volcán",
  ],
  "La Pampa": [
    "Santa Rosa","General Pico","Toay","Macachín","Eduardo Castex","Realicó",
    "General Acha","Victorica","Jacinto Aráuz","Guatraché","Doblas","Rancul","Trenel",
    "Alpachiri","Alta Italia","Anguil","Bernardo Larroude","Bernasconi","Catriló",
    "Embajador Martini","General Manuel Campos","Intendente Alvear","La Adela",
    "Lonquimay","Luan Toro","Metileo","Miguel Riglos","Naicó","Parera",
    "Quehué","Rolón","Sarah","Telén","Uriburu","Villa Mirasol","Winifreda",
  ],
  "La Rioja": [
    "La Rioja capital","Chilecito","Aimogasta","Chamical","Chepes","Villa Unión",
    "Vinchina","Nonogasta","Villa Sanagasta","Patquía","Famatina",
    "Castro Barros","Coronel Felipe Varela","General Ángel Vicente Peñaloza",
    "General Belgrano","General Lamadrid","General San Martín",
    "Rosario Vera Peñaloza","San Blas de los Sauces","Sanagasta","Arauco","Malanzan",
  ],
  "Mendoza": [
    "Mendoza capital","San Rafael","Godoy Cruz","Guaymallén","Las Heras","Luján de Cuyo",
    "Maipú","Rivadavia","Junín","General Alvear","Malargüe","San Martín",
    "Tupungato","Tunuyán","San Carlos","Lavalle","Palmira","Bowen","Potrerillos",
    "Agrelo","Cacheuta","Chacras de Coria","El Algarrobal","El Bermejo",
    "Eugenio Bustos","Fray Luis Beltrán","La Consulta","Las Catitas",
    "Los Árboles","Medrano","Montecaseros","Pareditas","Perdriel",
    "Rodeo del Medio","Rodeo de la Cruz","Russell","Santa Rosa","Villa Atuel","Vista Flores",
  ],
  "Misiones": [
    "Posadas","Oberá","Eldorado","Apóstoles","Jardín América","Leandro N. Alem",
    "Puerto Iguazú","Aristóbulo del Valle","Montecarlo","Campo Grande","Capioví",
    "San Pedro","Bernardo de Irigoyen","Wanda","Puerto Rico",
    "Alba Posse","Azara","Campo Viera","Candelaria","Caraguatay","Cerro Corá",
    "Comandante Andresito","Corpus","Dos de Mayo","El Soberbio","Garuhapé","Garupá",
    "Hipólito Yrigoyen","Itacaruaré","Loreto","Los Helechos","Mojón Grande",
    "Panambí","Puerto Esperanza","Puerto Leoni","Puerto Piray","Ruiz de Montoya",
    "San Ignacio","San Javier","San José","San Vicente","Santo Pipo",
  ],
  "Neuquén": [
    "Neuquén capital","Zapala","San Martín de los Andes","Cutral Có","Plaza Huincul",
    "Junín de los Andes","Centenario","Plottier","Rincón de los Sauces",
    "Chos Malal","Piedra del Águila","Aluminé","Loncopué","Villa La Angostura",
    "Añelo","Buta Ranquil","Caviahue-Copahue","El Cholar","El Huecú",
    "Huinganco","Las Lajas","Las Ovejas","Mariano Moreno","Minas","Picún Leufú",
    "San Patricio del Chañar","Senillosa","Tricao Malal","Villa El Chocón","Villa Pehuenia",
  ],
  "Río Negro": [
    "Viedma","San Carlos de Bariloche","General Roca","Cipolletti","Allen","El Bolsón",
    "Cinco Saltos","Catriel","San Antonio Oeste","Sierra Grande",
    "Jacobacci","Maquinchao","Los Menucos","Chimpay","Choele Choel",
    "Comallo","Conesa","Darwin","Dina Huapi","El Cuy","Fray Luis Beltrán",
    "General Fernández Oro","Guardia Mitre","Ing. Huergo","Lamarque","Las Grutas",
    "Ñorquinco","Pilcaniyeu","Pomona","Valcheta","Valle Azul","Villa Regina",
  ],
  "Salta": [
    "Salta capital","San Ramón de la Nueva Orán","Tartagal","Rosario de la Frontera",
    "General Güemes","Embarcación","Metán","Cafayate","Cachi",
    "San Antonio de los Cobres","Rosario de Lerma","La Caldera","Cerrillos","El Bordo",
    "Aguaray","Animaná","Campo Quijano","Chicoana","Coronel Moldes",
    "El Carril","El Galpón","El Quebrachal","Hipólito Yrigoyen","Iruya",
    "Joaquín V. González","Las Lajitas","Los Toldos","Nazareno","Payogasta",
    "Pichanal","Salvador Mazza","San Carlos","San José de Metán",
    "Santa Victoria Este","Santa Victoria Oeste","Seclantas","Urundel",
    "Villa San Lorenzo","Vaqueros","Yaví",
  ],
  "San Juan": [
    "San Juan capital","Rawson","Rivadavia","Caucete","Santa Lucía","Pocito",
    "Chimbas","9 de Julio","Albardón","Angaco","Calingasta","Jáchal","Iglesia","Ullum",
    "25 de Mayo","Barreal","Cañada Honda","Médano de Oro","Mogna","Niquivil",
    "Pismanta","Rodeo","San Agustín del Valle Fértil","San José de Jáchal","Sarmiento",
  ],
  "San Luis": [
    "San Luis capital","Villa Mercedes","Merlo","Justo Daract","La Toma","Quines",
    "Tilisarao","Santa Rosa del Conlara","Carpintería","Naschel","Luján","Concarán",
    "Alto Pelado","Alto Pencoso","Anchorena","Buena Esperanza","Candelaria","Carolina",
    "Cortaderas","El Trapiche","Fortuna","La Florida","La Punilla","Las Chacras",
    "Lafinur","Los Molles","Luyaba","Papagayos","Paso Grande","Renca","Saladillo",
    "San Francisco del Monte de Oro","San Martín","San Pablo","Santa Isabel",
    "Villa de la Quebrada","Villa del Carmen","Villa Larca","Villa General Roca",
  ],
  "Santa Cruz": [
    "Río Gallegos","Caleta Olivia","Pico Truncado","Las Heras","Perito Moreno",
    "El Calafate","El Chaltén","Puerto San Julián","Gobernador Gregores","Puerto Deseado",
    "28 de Noviembre","Comandante Luis Piedrabuena","Fitz Roy","Hipólito Yrigoyen",
    "Los Antiguos","Puerto Santa Cruz","Río Turbio","San Julián","Tres Lagos",
  ],
  "Santa Fe": [
    "Santa Fe capital","Rosario","Rafaela","Reconquista","Venado Tuerto","Villa Constitución",
    "San Lorenzo","Casilda","Esperanza","Las Rosas","Firmat","Cañada de Gómez",
    "Villa Gobernador Gálvez","Pérez","Gálvez","Sunchales","Santo Tomé",
    "Rufino","San Jorge","Tostado","Vera","Avellaneda","Calchaquí","San Cristóbal",
    "Álvarez","Armstrong","Arroyo Seco","Barrancas","Bigand","Bombal","Cañada Rosquín",
    "Capitán Bermúdez","Carcarañá","Carlos Pellegrini","Chañar Ladeado","Chovet",
    "Correa","El Trébol","Elortondo","Funes","Fuentes","General Lagos",
    "Granadero Baigorria","Ibarlucea","Laguna Paiva","Llambi Campbell","López",
    "Los Molinos","Maciel","Máximo Paz","Melincué","Nelson","Oliveros","Peyrano",
    "Puerto General San Martín","Ramona","Roldán","San Agustín","San Fabián",
    "San Genaro","San Guillermo","San Javier","San Justo","San Martín de las Escobas",
    "Sancti Spíritu","Santa Isabel","Sastre","Serodino","Soldini","Totoras",
    "Villa Ana","Villa Cañas","Villa Minetti","Villa Mugueta","Villa Trinidad",
    "Wheelwright","Zavalla",
  ],
  "Santiago del Estero": [
    "Santiago del Estero capital","La Banda","Frías","Loreto","Añatuya","Quimilí",
    "Monte Quemado","Fernández","Termas de Río Hondo","Villa Río Hondo",
    "Clodomira","Beltrán","Los Telares","Amamá","Averías","Campo Gallo",
    "Colonia El Simbolar","Colonia Dora","El Hoyo","Gramilla","Guardia Escolta",
    "Herrera","Huyamampa","Icaño","Isca Yacu","La Cañada","Las Tinajas",
    "Laprida","Lugones","Malbrán","Miraflores","Nueva Esperanza","Palo Negro",
    "Pampa de los Guanacos","Pozo Hondo","Sachayoj","Selva","Sol de Julio",
    "Sumamao","Suncho Corral","Tintina","Villa Atamisqui","Villa General Mitre",
    "Villa Salavina","Villa Unión","Vilmer",
  ],
  "Tierra del Fuego": [
    "Ushuaia","Río Grande","Tolhuin","Puerto Almanza","Lago Escondido",
  ],
  "Tucumán": [
    "San Miguel de Tucumán","Yerba Buena","Banda del Río Salí","Alderetes",
    "Concepción","Monteros","Aguilares","Famailla","Bella Vista","Lules",
    "Simoca","Tafí Viejo","Las Talitas","El Manantial","Juan Bautista Alberdi",
    "Tafí del Valle","Amaicha del Valle","Acheral","Burruyacu","Capitán Cáceres",
    "Chicligasta","Colalao del Valle","Colombres","Delfín Gallo","El Bracho",
    "El Cadillal","El Cercado","El Chañar","El Mollar","El Naranjo","El Naranjito",
    "Famaillá","Garmendia","Graneros","La Cocha","La Cruz","La Ramada","León Rouges",
    "Los Nogales","Los Ralos","Los Sarmientos","Monteagudo","Quilmes (Tucumán)",
    "Raco","Río Chico","San Andrés","San Pablo","Santa Lucía","Santa Rosa de Leales",
    "Tapia","Trancas","Villa Chiligasta","Villa de Leales","Vipos",
  ],
};

export const PROVINCIAS_LIST = Object.keys(MUNICIPIOS_POR_PROVINCIA);

/** Devuelve "Municipio, Provincia" o solo "Provincia" si no hay municipio */
export function buildZona(provincia: string, municipio: string): string {
  if (!provincia) return "";
  if (!municipio) return provincia;
  return `${municipio}, ${provincia}`;
}
